name: Crowdin Â» Upload keys

on:
  push:
    branches:
      - develop
      - r/*

concurrency:
  group: crowdin-${{ github.ref }}
  cancel-in-progress: true

jobs:
  upload-translation-keys:
    if: github.repository_owner == 'opencast'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Prepare crowdin client
      run: |
        wget --quiet https://artifacts.crowdin.com/repo/deb/crowdin3.deb
        sudo dpkg -i crowdin3.deb

    - name: Upload translation source
      env:
        CROWDIN_TOKEN: ${{ secrets.CROWDIN_TOKEN }}
      run: |
        crowdin upload sources --config .crowdin.yaml -b "${GITHUB_REF##*/}"
